name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Forge
title: "[Bug]: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter prompt '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Please paste any relevant error messages or logs. Run Forge with `--verbose` flag for detailed logs.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: shell

  - type: input
    id: version
    attributes:
      label: Forge Version
      description: What version of Forge are you running? (`forge --version`)
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Windows (WSL)
        - Windows (Native)
        - Other
    validations:
      required: false

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system?
      placeholder: e.g., macOS 14.1, Ubuntu 22.04
    validations:
      required: false

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider are you using?
      options:
        - OpenAI
        - Anthropic
        - OpenRouter
        - Google Vertex AI
        - Cerebras
        - x-ai
        - z.ai
        - Requesty
        - IO Intelligence
        - Groq
        - Amazon Bedrock
        - OpenAI-compatible
        - Other
    validations:
      required: false

  - type: input
    id: model
    attributes:
      label: Model
      description: Which model are you using?
      placeholder: e.g., claude-3.7-sonnet, gpt-4, o3-mini-high

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install Forge?
      options:
        - npx forgecode@latest
        - npm install -g forgecode
        - Built from source
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share relevant parts of your `forge.yaml` configuration (remove sensitive data like API keys).
      render: yaml
