name: ✨ Feature Request
description: Suggest a new feature or enhancement for Forge
title: "[Feature]: "
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        **Before you continue, please ensure you can clearly answer:**
        1. **Why do you NEED this feature?** (Not just "nice to have")
        2. **What is NOT possible right now?** (Current limitations)
        3. **What WILL be possible with this feature?** (Concrete outcomes)
        
        Vague or incomplete requests will be closed. Take your time to write a compelling case.

  - type: textarea
    id: why-needed
    attributes:
      label: "1. Why Do You NEED This Feature?"
      description: |
        **Be specific.** Explain the real-world problem or blocker you're facing.
        Not "it would be cool if..." but "I cannot accomplish X because..."
        Why is this important to your workflow? What is the impact of NOT having this?
      placeholder: |
        I NEED this feature because:
        - Current workflow requires me to...
        - This costs me X hours per week...
        - Without this, I cannot accomplish...
        - The business impact is...
    validations:
      required: true

  - type: textarea
    id: current-limitation
    attributes:
      label: "2. What Is NOT Possible Right Now?"
      description: |
        **Describe the current limitations in detail.**
        What have you tried? What doesn't work? Why can't you work around it?
        Include specific examples, commands, or workflows that fail.
      placeholder: |
        Currently, I cannot:
        - [Specific action/workflow that fails]
        - [What happens when you try]
        - [Why existing features don't solve this]
        
        I've tried:
        - [Workaround 1 and why it doesn't work]
        - [Workaround 2 and why it doesn't work]
    validations:
      required: true

  - type: textarea
    id: future-possibilities
    attributes:
      label: "3. What WILL Be Possible With This Feature?"
      description: |
        **Describe concrete outcomes and capabilities.**
        What specific tasks/workflows will this enable?
        How will your work change? What new things can you build/do?
      placeholder: |
        With this feature, I will be able to:
        - [Specific new capability 1]
        - [Specific new capability 2]
        - [Measurable improvement: time saved, errors reduced, etc.]
        
        Example workflow:
        ```
        # Show the exact commands or steps you'll use
        forge new-feature --example
        ```
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution (User Experience)
      description: |
        **Focus on the user experience, not implementation details.**
        How would a user interact with this feature? What would they see/do?
        Save technical implementation details for "Implementation Ideas" below.
      placeholder: |
        From a user's perspective, the feature should work like this:
        - When I [action], I would see/get [result]
        - The interaction would be: [step-by-step user flow]
        - Example: "When I run `forge search docs`, I'd see matching results from Google Workspace"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also thought about...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        1. As a developer, I want to...
        2. When working on large projects, I need to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - AI/LLM Integration
        - Code Generation/Editing
        - File Operations
        - Configuration
        - CLI/UX
        - Documentation
        - Performance
        - Security
        - MCP Integration
        - Multi-Agent Workflows
        - Shell Plugin
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Tools
      description: Are there similar features in other tools that could serve as inspiration?
      placeholder: Tool X does this by...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have any ideas about how this could be implemented, share them here.
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
  
  - type: checkboxes
    id: requirements-check
    attributes:
      label: "✅ Pre-submission Checklist"
      description: "Before submitting, confirm you've addressed all requirements:"
      options:
        - label: "I have clearly explained WHY I need this feature (not just that it would be nice)"
          required: true
        - label: "I have described what is NOT currently possible in detail"
          required: true
        - label: "I have explained what WILL be possible with concrete examples"
          required: true
        - label: "I have provided specific use cases and workflows"
          required: true
        - label: "I have searched existing issues to avoid duplicates"
          required: true
